#ifndef _YRENDER_VKRHI_VKCONFIG_H_
#define _YRENDER_VKRHI_VKCONFIG_H_


//Vulkan configure
#define VULKAN_HAS_DEBUGGING_ENABLED 0

//#define VULKAN_SUPPORTS_DEBUG_UTILS 1

//#define VULKAN_EXT_SWAPCHIAN_COLORSPACE 1

#endif